
spring.datasource:
  url: jdbc:postgresql://localhost:5498/test
  username: test
  password: test
  jpa:
    open-in-view: false
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: validate
    show-sql: true
server:
  port: 80
